formation_atp_core:
    resource: "@formationATPCoreBundle/Resources/config/routing.yml"
    prefix:   /

formation_atp:
    resource: "@formationATPMoviesBundle/resources/config/routing.yml"
    prefix: /

